"""Backtest engine, metrics, plotting, exports, and parameter sweeps."""
from .engine import BacktestResult, Trade, execution_bars, run_backtest
from .metrics import (
    VERDICT_LOWER_RETURN_LOWER_DD,
    VERDICT_OUTPERFORMS_BH,
    VERDICT_UNDERPERFORMS_BH,
    Metrics,
    benchmark_verdict,
    compute_metrics,
)
from .plotting import plot_equity_curve
from .reports import (
    DEBUG_TRADE_COLUMNS,
    TRADE_COLUMNS,
    debug_trades_dataframe,
    trades_to_dataframe,
    write_debug_trades_csv,
    write_trades_csv,
)
from .sweep import (
    REGIME_SWEEP_COLUMNS,
    SWEEP_COLUMNS,
    run_regime_sma_sweep,
    run_sma_sweep,
)
from .compare import (
    COMPARISON_COLUMNS,
    DEFAULT_COMPARISON_STRATEGIES,
    DEFAULT_SUBPERIODS,
    StrategySpec,
    Subperiod,
    render_comparison_markdown,
    run_comparison_report,
)
from .cross_sectional import (
    CrossSectionalResult,
    run_cross_sectional_momentum,
    run_cross_sectional_reversal,
)
from .dsr import (
    deflated_sharpe_from_trial_sharpes,
    deflated_sharpe_ratio,
    expected_max_sharpe,
    sharpe_ratio_per_period,
)
from .multi_asset import (
    MULTI_ASSET_AGGREGATE_COLUMNS,
    MULTI_ASSET_DETAIL_COLUMNS,
    MULTI_ASSET_SUMMARY_COLUMNS,
    aggregate_multi_asset,
    run_multi_asset_yearly_validation,
    summarize_across_assets,
)
from .yearly import (
    DEFAULT_FIXED_STRATEGIES,
    FixedStrategySpec,
    VERDICT_BUY_AND_HOLD,
    YEARLY_AGGREGATE_COLUMNS,
    YEARLY_COLUMNS,
    aggregate_yearly_results,
    run_yearly_validation,
)
from .walk_forward import (
    MULTI_WALK_FORWARD_COLUMNS,
    OBJECTIVE_RETURN_DIV_DRAWDOWN,
    OBJECTIVE_TOTAL_RETURN,
    WALK_FORWARD_COLUMNS,
    WalkForwardWindow,
    generate_windows,
    run_multi_walk_forward,
    run_sma_walk_forward,
)
from .walk_forward_v2 import (
    OBJECTIVE_SHARPE,
    PROJECT_NUM_TRIALS,
    STRATEGY_WALK_FORWARD_COLUMNS,
    ParamGridSpec,
    WindowSpec,
    aggregate_walk_forward,
    generate_month_windows,
    run_strategy_walk_forward,
)
from .walk_forward_grids import (
    build_pma_grid,
    build_sma_grid,
    build_tsmom_grid,
)
from .ensemble import (
    EnsembleResult,
    SleeveSpec,
    compute_portfolio_metrics,
    correlation_summary,
    run_ensemble_walk_forward,
    sortino_ratio,
)
from .ensemble_sleeves import DEFAULT_ASSETS, default_sleeves
from .market_index import build_crypto_market_index
from .cluster_stability import (
    ClusterStabilityResult, run_cluster_stability_check,
)

__all__ = [
    "BacktestResult",
    "DEBUG_TRADE_COLUMNS",
    "DEFAULT_FIXED_STRATEGIES",
    "FixedStrategySpec",
    "Metrics",
    "COMPARISON_COLUMNS",
    "CrossSectionalResult",
    "DEFAULT_COMPARISON_STRATEGIES",
    "DEFAULT_SUBPERIODS",
    "MULTI_ASSET_AGGREGATE_COLUMNS",
    "MULTI_ASSET_DETAIL_COLUMNS",
    "MULTI_ASSET_SUMMARY_COLUMNS",
    "MULTI_WALK_FORWARD_COLUMNS",
    "OBJECTIVE_RETURN_DIV_DRAWDOWN",
    "OBJECTIVE_SHARPE",
    "OBJECTIVE_TOTAL_RETURN",
    "PROJECT_NUM_TRIALS",
    "ParamGridSpec",
    "STRATEGY_WALK_FORWARD_COLUMNS",
    "WindowSpec",
    "aggregate_walk_forward",
    "DEFAULT_ASSETS",
    "EnsembleResult",
    "build_crypto_market_index",
    "ClusterStabilityResult",
    "run_cluster_stability_check",
    "SleeveSpec",
    "build_pma_grid",
    "build_sma_grid",
    "build_tsmom_grid",
    "compute_portfolio_metrics",
    "correlation_summary",
    "default_sleeves",
    "run_ensemble_walk_forward",
    "sortino_ratio",
    "generate_month_windows",
    "run_strategy_walk_forward",
    "REGIME_SWEEP_COLUMNS",
    "SWEEP_COLUMNS",
    "TRADE_COLUMNS",
    "Trade",
    "VERDICT_BUY_AND_HOLD",
    "VERDICT_LOWER_RETURN_LOWER_DD",
    "VERDICT_OUTPERFORMS_BH",
    "VERDICT_UNDERPERFORMS_BH",
    "WALK_FORWARD_COLUMNS",
    "StrategySpec",
    "Subperiod",
    "WalkForwardWindow",
    "YEARLY_AGGREGATE_COLUMNS",
    "YEARLY_COLUMNS",
    "aggregate_multi_asset",
    "aggregate_yearly_results",
    "benchmark_verdict",
    "compute_metrics",
    "debug_trades_dataframe",
    "deflated_sharpe_from_trial_sharpes",
    "deflated_sharpe_ratio",
    "expected_max_sharpe",
    "sharpe_ratio_per_period",
    "execution_bars",
    "render_comparison_markdown",
    "run_comparison_report",
    "run_cross_sectional_momentum",
    "run_cross_sectional_reversal",
    "generate_windows",
    "plot_equity_curve",
    "run_backtest",
    "run_multi_asset_yearly_validation",
    "run_multi_walk_forward",
    "run_regime_sma_sweep",
    "run_sma_sweep",
    "run_sma_walk_forward",
    "run_yearly_validation",
    "summarize_across_assets",
    "trades_to_dataframe",
    "write_debug_trades_csv",
    "write_trades_csv",
]
